// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
// import ToastProvider from "@/providers/ToastProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ToastProvider />
//         <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
//       </body>
//     </html>
//   );
// }
// RootLayout.js

import React from "react";
import { Provider } from "react-redux";
// import store from "../redux/store/store"; // Import your Redux store
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import ToastProvider from "@/providers/ToastProvider";
import { IBM_Plex_Mono } from "next/font/google";

import "./globals.css";

const inter = IBM_Plex_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: any) => {
  return (
    // <Provider store={store}>
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
    // </Provider>
  );
};

export default RootLayout;
